package gate.creole.infertagger.test
import gate.creole.infertagger.rules.*;
import gate.creole.infertagger.rulemodel.*;

declare Player
	@Marker("MarkRel")	
	name : String @Feature
	surname : String @Feature
	startRel : Annotation @From
	endRel : Annotation @To
end	

rule "Find player"
    when
    	$player : Word( string == "player" )
    	$name : Word( category == "NNP", orth == "upperInitial" )
    	$surname : Word( category == "NNP", orth == "upperInitial" )
  		order($player, $name, $surname;)  	
    then
        insert(new Player($name.getString(), $surname.getString(), $name, $surname));
end