package gate.creole.infertagger.test

import gate.creole.infertagger.rulemodel.*;
import java.util.*

declare MyMarker
	@Marker("Mark")	
	feature : String @Feature
	anno : Annotation @From
end

rule "Marker test"
    dialect "mvel"
    when
    	$t : Token(string == "super")
    then
    	insert(new MyMarker("good", $t))
end

declare MyMarkerRel
	@Marker("MarkRel")	
	feature : String @Feature
	anno : Annotation @From
	anno2 : Annotation @To
end		

rule "Marker Relation test"
    dialect "mvel"
    when
    	$t : Token(string == "super")
    	$t2 : Token(string == "Token")
    then
    	insert(new MyMarkerRel("good2", $t2, $t))
end